server {
    listen 8883 ssl;
    js_preread reject.check;
    # EMQXアドオン名またはアドレスに合わせて変更してください
    proxy_pass a0d7b954-emqx:1883;

    ssl_certificate     /ssl/fullchain.pem;
    ssl_certificate_key /ssl/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL_MQTT:10m;
    ssl_session_timeout 1h;
}
